const { seed_plant } = require("./plant.js");

const additional_plants = async ({
  growth,
  life,
  plant_sz,
  plant_st,
  shape,
  soil,
  sun,
  user,
  water,
  zn,
}) => {
  const [plant5, plant6, plant7] = [
    seed_plant({
      plant_name: "Ruby Moon",
      plant_description: "Hyacinth Bean",
      max_height: "72in",
      max_width: "20in",
      bloom_time: "Late Summer",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[1].id,
      soil_requirement_id: soil[2].id,
      growth_habit_id: growth[1].id,
      life_cycle_id: life[0].id,
    }),
    seed_plant({
      plant_name: "MoSilver Dollar Plant",
      plant_description: "Plectranthus Argentatus",
      max_height: "32in - 36in",
      max_width: "20in",
      bloom_time: "Summer - Fall",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[1].id,
      soil_requirement_id: soil[0].id,
      growth_habit_id: growth[0].id,
      life_cycle_id: life[0].id,
    }),
    seed_plant({
      plant_name: "Pink Crystals Ruby Grass",
      plant_description: "Melinis Nerviglumis",
      max_height: "20-24in",
      max_width: "15in",
      bloom_time: "August",
      zone_id: zn[7].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[3].id,
      growth_habit_id: growth[2].id,
      life_cycle_id: life[0].id,
    }),
  ];

  const [plant8, plant9, plant10] = [
    seed_plant({
      plant_name: "Vermillion Bluffs Mexican Sage",
      plant_description: "Salvia",
      max_height: "40in",
      max_width: "20in",
      bloom_time: "August - October",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[2].id,
      growth_habit_id: growth[0].id,
      life_cycle_id: life[1].id,
    }),
    seed_plant({
      plant_name: "Moon Carrot",
      plant_description: "Seseli Gummiferum",
      max_height: "32in - 36in",
      max_width: "20in",
      bloom_time: "Mid Summer - Fall",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[0].id,
      growth_habit_id: growth[1].id,
      life_cycle_id: life[1].id,
    }),
    seed_plant({
      plant_name: "Giant Sacaton",
      plant_description: "Sporobolus Wrightii",
      max_height: "60in",
      max_width: "15in",
      bloom_time: "Late Summer - Fall",
      zone_id: zn[7].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[3].id,
      growth_habit_id: growth[1].id,
      life_cycle_id: life[1].id,
    }),
  ];

  const [plant11, plant12, plant13] = [
    seed_plant({
      plant_name: "Hopflower Oregano",
      plant_description: "Origanum Libanoticum",
      max_height: "12in",
      max_width: "8in",
      bloom_time: "August - October",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[2].id,
      soil_requirement_id: soil[0].id,
      growth_habit_id: growth[0].id,
      life_cycle_id: life[1].id,
    }),
    seed_plant({
      plant_name: "Silverton Bluemat Penstemon",
      plant_description: "Penstemon",
      max_height: "12in",
      max_width: "12in",
      bloom_time: "May-June",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[0].id,
      growth_habit_id: growth[1].id,
      life_cycle_id: life[1].id,
    }),
    seed_plant({
      plant_name: "Snowmas Phlox",
      plant_description: "Phlox Bifida",
      max_height: "12in",
      max_width: "12in",
      bloom_time: "Late Summer - Fall",
      zone_id: zn[7].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[3].id,
      growth_habit_id: growth[1].id,
      life_cycle_id: life[1].id,
    }),
  ];

  const [plant14, plant15, plant16] = [
    seed_plant({
      plant_name: "Alpine Willow Herb",
      plant_description: "Epilobium Fleischeri",
      max_height: "18in",
      max_width: "12in",
      bloom_time: "Spring-Fall",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[2].id,
      soil_requirement_id: soil[2].id,
      growth_habit_id: growth[0].id,
      life_cycle_id: life[1].id,
    }),
    seed_plant({
      plant_name: "Spanish Peaks Foxglove",
      plant_description: "Digitalis Thapsi",
      max_height: "20in",
      max_width: "12in",
      bloom_time: "April-August",
      zone_id: zn[8].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[0].id,
      growth_habit_id: growth[1].id,
      life_cycle_id: life[1].id,
    }),
    seed_plant({
      plant_name: "Coronado Hyssop",
      plant_description: "Sonoran Sunset Hyssop",
      max_height: "18in",
      max_width: "10in",
      bloom_time: "Late Summer - Fall",
      zone_id: zn[7].id,
      water_requirement_id: water[1].id,
      sun_requirement_id: sun[0].id,
      soil_requirement_id: soil[3].id,
      growth_habit_id: growth[1].id,
      life_cycle_id: life[1].id,
    }),
  ];
};

module.exports = { additional_plants };
